'use strict';
function createSaunaLocationPicker({lat,lng,allowed=true,getAddress=()=>''}){
  const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
  const root=el('fieldset');root.className='sauna-location-picker';root.append(el('legend','Where is your sauna?'),el('p','Place the pin at the entrance guests should use. We’ll save the map location for you.'));
  const original=SeanaMapLocation.point(lat,lng);let saved=original,draft=original,dirty=false,map,marker,disposed=false;
  const latitude=el('input'),longitude=el('input');latitude.type=longitude.type='hidden';latitude.name='lat';longitude.name='lng';latitude.value=original?.lat??'';longitude.value=original?.lng??'';root.append(latitude,longitude);
  const status=el('p',original?'Your saved map pin is ready to review.':'No map pin saved yet.');status.setAttribute('role','status');root.append(status);
  const controls=el('div');controls.className='location-actions';
  const button=(label,fn)=>{const b=el('button',label);b.type='button';b.disabled=!allowed;b.addEventListener('click',fn);return b;};
  const canvas=el('div');canvas.className='sauna-pin-map';canvas.hidden=true;canvas.setAttribute('aria-label','Sauna entrance map');
  const error=el('p');error.setAttribute('role','status');error.className='location-map-error';
  const icon=()=>L.divIcon({className:'sauna-map-marker',html:'<span aria-hidden="true">●</span>',iconSize:[30,30],iconAnchor:[15,15]});
  function paint(){if(!map||!draft)return;if(!marker){marker=L.marker([draft.lat,draft.lng],{draggable:allowed,icon:icon(),title:'Sauna entrance pin'}).addTo(map);marker.on('dragend',()=>{const p=marker.getLatLng();choose(p.lat,p.lng);});}else marker.setLatLng([draft.lat,draft.lng]);}
  function open(){if(disposed)return false;canvas.hidden=false;if(!window.L){error.textContent='The map could not load. Refresh this page and try again.';return false;}if(!map){map=L.map(canvas,{scrollWheelZoom:false}).setView(draft?[draft.lat,draft.lng]:[53.4,-8],draft?15:6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>{error.textContent='Map imagery could not load. Check your connection before confirming the pin.';}).addTo(map);map.on('click',event=>{if(allowed)choose(event.latlng.lat,event.latlng.lng);});paint();}requestAnimationFrame(()=>{if(!disposed)map.invalidateSize();});return true;}
  function choose(a,b){const p=SeanaMapLocation.point(a,b);if(!p||!allowed||disposed)return;draft=p;dirty=true;confirm.disabled=false;status.textContent='Check the pin, move it if needed, then confirm this entrance.';paint();}
  const confirm=button('Confirm this entrance',()=>{if(!draft||!open())return;saved={...draft};latitude.value=saved.lat.toFixed(6);longitude.value=saved.lng.toFixed(6);dirty=false;confirm.disabled=true;status.textContent='Entrance pin confirmed. Save your sauna details to apply it.';});confirm.disabled=true;
  controls.append(button(original?'Review or move pin':'Choose location on map',open));
  controls.append(button('Use my location at the sauna',()=>{if(!navigator.geolocation){status.textContent='Location is unavailable. Choose the entrance on the map instead.';return;}status.textContent='Finding your location…';navigator.geolocation.getCurrentPosition(position=>{if(disposed)return;if(open()){choose(position.coords.latitude,position.coords.longitude);map.setView([draft.lat,draft.lng],17);}},()=>{if(!disposed)status.textContent='Location access was unavailable. You can still place your pin on the map.';},{enableHighAccuracy:true,timeout:12000,maximumAge:0});}));
  const search=el('a','Find my sauna in Google Maps ↗');search.target='_blank';search.rel='noopener noreferrer';search.href='https://www.google.com/maps';search.addEventListener('click',()=>{search.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(getAddress()||'saunas Ireland');});controls.append(search);root.append(controls);
  const detail=el('details'),summary=el('summary','Already have a map link?');detail.append(summary,el('p','Open your sauna in Google Maps and copy the full address from your browser. Paste it here, then check the pin.'));
  const label=el('label','Map link'),link=el('input');link.type='text';link.inputMode='url';link.setAttribute('data-map-link','');link.placeholder='Paste your sauna’s Google Maps link';link.disabled=!allowed;label.append(link);detail.append(label,button('Find pin from link',()=>{let p;try{p=SeanaMapLocation.fromLink(link.value);}catch{}if(!p){status.textContent='This link does not include a map pin. Open it in your browser and copy the full address, or choose the entrance directly on our map.';return;}if(open()){choose(p.lat,p.lng);map.setView([p.lat,p.lng],17);}}));root.append(detail,canvas,error);
  const pinActions=el('div');pinActions.className='location-actions';pinActions.append(button('Place pin in centre of map',()=>{if(open()){const p=map.getCenter();choose(p.lat,p.lng);}}),confirm,button('Keep saved pin',()=>{draft=saved;dirty=false;confirm.disabled=true;if(marker){map.removeLayer(marker);marker=null;}paint();if(map&&saved)map.setView([saved.lat,saved.lng],15);status.textContent=saved?'Keeping your confirmed pin.':'No pin selected. Choose your sauna entrance.';}));root.append(pinActions,el('p','Only use your current location while you are at the sauna. You can zoom with + / − and move the pin to the correct entrance.'));
  root.markSaved=()=>{status.textContent=saved?'Your sauna entrance pin is saved.':'No map pin saved yet.';};
  root.validate=()=>{if(dirty)throw Error('Confirm your new map pin before saving the sauna.');};
  root.resetPin=()=>{saved=draft=null;dirty=false;latitude.value=longitude.value='';confirm.disabled=true;if(marker){map.removeLayer(marker);marker=null;}status.textContent='No map pin saved yet.';};
  root.dispose=()=>{disposed=true;if(map)map.remove();};return root;
}
