/* Location-scoped plans. Prices and allowances are immutable after creation. */
function createMembershipPlansPanel({api,saunaId,canWrite}) {
 const el=(tag,text)=>{const n=document.createElement(tag);n.textContent=text||'';return n;};
 const root=el('section');root.className='panel';root.append(el('h2','Memberships'),el('p','Build a regular sauna ritual. Choose benefits only or include regular sessions each billing period. Existing members keep the price and allowance they joined with.'));
 const status=el('p');status.setAttribute('role','status');const list=el('div'),form=el('form');form.className='form-grid';
 const input=(label,type,value)=>{const l=el('label',label),n=el('input');n.type=type;n.value=value;n.required=true;l.append(n);form.append(l);return n;};
 const name=input('Membership name','text',''),price=input('Price in euro per renewal','number',''),benefits=input('Benefits and how to use them','text','');name.maxLength=80;benefits.maxLength=1500;benefits.minLength=10;price.min='1';price.max='1000';price.step='0.01';
 const frequency=el('select');for(const [v,label] of [['month','Every month'],['week','Every week'],['year','Every year']]){const o=el('option',label);o.value=v;frequency.append(o);}const fl=el('label','Billing frequency');fl.append(frequency);form.append(fl);
 const kind=el('select');for(const [v,label] of [['0','Benefits only — bookings charged separately'],['1','Include regular sessions each billing period']]){const o=el('option',label);o.value=v;kind.append(o);}const kl=el('label','Membership includes');kl.append(kind);form.append(kl);
 const count=input('Included regular sessions per period','number','4');count.min='1';count.max='100';count.step='1';count.parentElement.style.display='none';kind.onchange=()=>{count.parentElement.style.display=kind.value==='0'?'none':'';};
 form.append(el('p','Included sessions: one person per booking, regular sessions only, subject to availability. Use within the paid billing period; no rollover. Special session types and socials are booked separately. Cancellation stops the next renewal.'));
 const refresh=el('button','Refresh memberships');refresh.type='button';refresh.className='secondary';
 const add=el('button','Create membership');add.disabled=!canWrite;form.append(add);root.append(refresh,status,list,form);
 let busy=false;
 async function call(path,options){const r=await api(path,options);if(!r.ok)throw Error(r.body?.error||'Please try again.');return r.body;}
 async function load(){const data=await call(`/api/business/${encodeURIComponent(saunaId)}/membership-plans`);list.replaceChildren();for(const p of data.plans){const card=el('article');card.className='panel';card.append(el('h3',p.name),el('p',`€${(p.amount_cents/100).toFixed(2)} / ${p.interval} · ${p.sessions_per_period?p.sessions_per_period+' regular sessions':'Benefits only'} · ${p.active?'Available':'Archived'}`),el('p',p.benefits),el('p',`${p.members||0} active members`));if(p.active&&canWrite){const archive=el('button','Stop new subscriptions');archive.type='button';archive.onclick=async()=>{if(!confirm('Stop new subscriptions? Existing memberships continue at their agreed price and allowance.'))return;archive.disabled=true;try{await call(`/api/business/${saunaId}/membership-plans/${p.id}/archive`,{method:'POST',body:'{}'});await load();}catch(e){status.textContent=e.message;archive.disabled=false;}};card.append(archive);}list.append(card);}if(!data.plans.length)list.append(el('p','No memberships yet. Create your first plan below.'));}
 form.onsubmit=async e=>{e.preventDefault();if(busy||!canWrite)return;busy=true;add.disabled=true;status.textContent='Saving membership…';try{await call(`/api/business/${saunaId}/membership-plans`,{method:'POST',body:JSON.stringify({name:name.value,benefits:benefits.value,amountCents:Math.round(Number(price.value)*100),interval:frequency.value,sessionsPerPeriod:kind.value==='1'?Number(count.value):0})});await load();form.reset();count.value='4';count.parentElement.style.display='none';status.textContent='Membership created. Customers can subscribe from this sauna in the app once Stripe is ready.';}catch(e){status.textContent=e.message;}finally{busy=false;add.disabled=!canWrite;}};
 refresh.onclick=async()=>{if(refresh.disabled)return;refresh.disabled=true;status.textContent='Checking memberships…';try{await load();status.textContent='Memberships and active member counts are up to date.';}catch(e){status.textContent=e.message;}finally{refresh.disabled=false;}};
 void load().catch(e=>status.textContent=e.message);return root;
}
