/* Owner-managed special sessions. Every request is scoped to the selected sauna. */
function createSessionTypesPanel({api, saunaId, canWrite}) {
  const panel=document.createElement('section');panel.className='panel';panel.style.marginTop='16px';
  const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
  const heading=el('h2','Special session types'),note=el('p','Choose an audience such as Women only, plus a price, capacity and weekly times for each session. They appear in your sauna’s Sessions tab. Inactive sessions stop accepting new bookings; existing bookings stay in place.'),list=el('div'),editor=el('div'),status=el('p');status.setAttribute('role','status');
  let options, saving=false;
  const add=el('button','Add a session type');add.type='button';add.disabled=true;add.onclick=()=>edit();
  panel.append(heading,note,list,add,editor,status);
  const base='/api/business/'+encodeURIComponent(saunaId)+'/session-types';
  async function load(){if(!options){const response=await api('/api/session-type-options');if(!response.ok)throw Error('Could not load session options');options=response.body;add.disabled=!canWrite;}const response=await api(base);if(!response.ok)throw Error(response.body?.error||'Could not load sessions');list.replaceChildren();for(const type of response.body){const row=el('div'),text=el('p',`${type.name} · €${(type.priceCents/100).toFixed(2)} · ${type.capacity} people${type.active?'':' · inactive'}${(type.tags||[]).map(tag=>' · '+([...options.audiences,...options.experiences].find(option=>option.id===tag)?.label||tag)).join('')}`),button=el('button','Edit '+type.name);row.className='session-row';button.className='secondary';button.type='button';button.disabled=!canWrite;button.onclick=()=>{if(!saving)edit(type);};row.append(text,button);list.append(row);}}
  function edit(type){
    if(saving||!options||!canWrite)return;
    editor.replaceChildren();status.textContent='';const form=el('form');form.className='form-grid';form.style.marginTop='20px';const fields={};
    for(const [key,label,inputType,value] of [['name','Session name','text',type?.name||''],['description','Description','text',type?.description||''],['price','Price per person (€)','number',type?type.priceCents/100:''],['capacity','People per session','number',type?.capacity||'']]){const wrapper=el('label',label),input=el('input');input.type=inputType;input.value=value;input.required=key!=='description';input.disabled=!canWrite;if(inputType==='number'){input.min=key==='price'?'0':'1';input.max=key==='price'?'10000':'500';input.step=key==='price'?'0.01':'1';}else input.maxLength=key==='name'?160:5000;wrapper.append(input);form.append(wrapper);fields[key]=input;}
    const audienceLabel=el('label','Who is this session for?'),audience=el('select');
    for(const option of options.audiences){const node=el('option',option.label);node.value=option.id;audience.append(node);}
    audience.value=options.audiences.find(option=>option.id&&(type?.tags||[]).includes(option.id))?.id||'';
    audience.disabled=!canWrite;audienceLabel.append(audience);form.append(audienceLabel,el('p','Guests see this label before booking. Explain any participation requirements in the description.'));
    const styles=el('fieldset');styles.append(el('legend','Session style (optional)'));const styleInputs=[];
    for(const option of options.experiences){const label=el('label',option.label),input=el('input');input.type='checkbox';input.checked=(type?.tags||[]).includes(option.id);input.disabled=!canWrite;label.prepend(input);styles.append(label);styleInputs.push({id:option.id,input});}form.append(styles);
    const activeLabel=el('label','Accept new bookings'),active=el('input');active.type='checkbox';active.checked=type?.active!==false;active.disabled=!canWrite;activeLabel.prepend(active);form.append(activeLabel);
    const hours=el('fieldset'),legend=el('legend','Session days & times');hours.className='weekly-hours';hours.append(legend,el('p','One session on each enabled day. All times are local to Ireland.'));const days=[];
    for(const day of ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']){const saved=type?.schedule?.find(entry=>entry.day===day),row=el('div'),label=el('label',day[0].toUpperCase()+day.slice(1)),enabled=el('input'),start=el('input'),end=el('input');enabled.type='checkbox';enabled.checked=!!saved;enabled.disabled=!canWrite;label.prepend(enabled);start.value=saved?.startTime||'09:00';end.value=saved?.endTime||'10:00';start.maxLength=end.maxLength=5;start.setAttribute('aria-label',day+' session start');end.setAttribute('aria-label',day+' session end');const toggle=()=>{start.disabled=end.disabled=!enabled.checked||!canWrite;start.required=end.required=enabled.checked;};enabled.onchange=toggle;toggle();row.append(label,start,el('span',' to '),end);hours.append(row);days.push({day,enabled,start,end});}form.append(hours);
    const save=el('button','Save session type'),cancel=el('button','Cancel editing');save.type='submit';save.disabled=!canWrite;cancel.type='button';cancel.onclick=()=>editor.replaceChildren();form.append(save,cancel);editor.append(form);
    form.onsubmit=async event=>{event.preventDefault();if(saving||!canWrite)return;saving=true;const controls=[...form.querySelectorAll('input,select,button')].map(node=>({node,disabled:node.disabled}));controls.forEach(({node})=>{node.disabled=true;});save.disabled=cancel.disabled=true;add.disabled=true;status.textContent='Saving…';try{const body={name:fields.name.value,description:fields.description.value,priceCents:Math.round(Number(fields.price.value)*100),capacity:Number(fields.capacity.value),active:active.checked,tags:[...(audience.value?[audience.value]:[]),...styleInputs.filter(style=>style.input.checked).map(style=>style.id)],schedule:days.filter(d=>d.enabled.checked).map(d=>({day:d.day,startTime:d.start.value,endTime:d.end.value}))};const response=await api(base+(type?'/'+encodeURIComponent(type.id):''),{method:type?'PUT':'POST',body:JSON.stringify(body)});if(!response.ok)throw Error(response.body?.error||'Could not save session');editor.replaceChildren();status.textContent=active.checked?'Session published with its audience, price and timetable.':'Session saved as inactive. It is hidden from guests.';try{await load();}catch(_){status.textContent='Session saved. Reopen this location to refresh the list.';}}catch(error){status.textContent=error.message;}finally{saving=false;controls.forEach(({node,disabled})=>{node.disabled=disabled;});save.disabled=cancel.disabled=!canWrite;add.disabled=!canWrite;}};
  }
  void load().catch(error=>{status.textContent=error.message;const retry=el('button','Retry loading sessions');retry.type='button';retry.onclick=()=>{retry.disabled=true;void load().then(()=>{retry.remove();status.textContent='';}).catch(error=>{status.textContent=error.message;retry.disabled=false;});};panel.append(retry);});
  return panel;
}
